# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
    
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: rhinogram/node-awscli

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn lint
      - run: yarn test
      - run: yarn build
      - persist_to_workspace: 
          root: ~/repo
          paths:
            - dist
            - script
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - deploy:
          command: script/deploy-prod

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - promote:
          requires:
            - build
          filters:
            branches:
              only: master
          type: approval
      - deploy:
          requires:
            - promote
          filters:
            branches:
              only: master